# PyTorch Basics

In [1]:
import torch

## Tensors

A tensor is a scalar number, a vector, a matrix, or any n-dimensional array

A scalar

In [3]:
t1 = torch.tensor(4.)
t1 

tensor(4.)

Check the type using <code>.type</code>

In [4]:
t1.dtype

torch.float32

A vector

In [6]:
t2 = torch.tensor([1.,2,3])
t2

tensor([1., 2., 3.])

Notice that PyTorch transforms to float if at least one element is a float

A matrix

In [8]:
t3 = torch.tensor([[1.,2,3],[4,5,6]])
t3

tensor([[1., 2., 3.],
        [4., 5., 6.]])

A 3D array

In [10]:
t4 = torch.tensor(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [7,8,9],
            [10,11,12.]
        ]
    ]
)
t4

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

### Attributes

To check the dimension lenghts of a tensor use <code>.shape</code>

In [11]:
t4.shape

torch.Size([2, 2, 3])

### Operations

It is possible to combine tensors using usal mathematical operations

In [28]:
x = torch.tensor(2., requires_grad=True)
w = torch.tensor(3., requires_grad=False)
b = torch.tensor(4., requires_grad=False)

Setting the parameter <code>requires_grad</code> to True make sure that PyTorch will automatically track and calculate gradients for that tensor

$$y = w * x^{2} + b = 3 * 2^{2} + 4 = 16$$

In [29]:
y = w * x ** 2 + b
y

tensor(16., grad_fn=<AddBackward0>)

To compute the derivatives use <code>.backward</code>

In [30]:
y.backward()

$$\frac{dy}{dx} = 2 * w * x = 2 * 3 * 2 = 12$$

In [31]:
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/db', b.grad)

dy/dx tensor(12.)
dy/dw None
dy/db None


## Interoperability with numpy

In [32]:
import numpy as np

It is possible to transform a numpy array in a torch tensor
- <code>torch.from_numpy()</code> uses the same memory space of the numpy array, so it gets substituted
- <code>torch.tensor()</code> creates a copy of the numpy array

In [41]:
n1 = np.array([[1,2,3],[4,5,6.]])
n1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
t1 = torch.from_numpy(n1)
t1

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

To create a numpy array from a torch tensor use <code>.numpy()</code>

In [42]:
n1 = t1.numpy()
n1

array([[1., 2., 3.],
       [4., 5., 6.]])