In [58]:
import torch
import numpy as np

# GPU usage

Check if PyTorch can use the GPU

In [80]:
print(f"Is GPU detected?\t\t{torch.cuda.is_available()}")
print(f"How many GPUs are detected?\t{torch.cuda.device_count()}")
print(f"GPU's name in use\t\t{torch.cuda.get_device_name(torch.cuda.current_device())}")

Is GPU detected?		True
How many GPUs are detected?	1
GPU's name in use		NVIDIA GeForce RTX 2070 with Max-Q Design


To set the default for new tensors to use the GPU

In [16]:
# torch.set_default_tensor_type(torch.cuda.FloatTensor)

To set a variable that allows to move tensors to the GPU (if available)

In [30]:
torch_device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print(torch_device)

cuda


To move a tensor to the GPU

In [81]:
rand_tensor = torch.rand(100)
print(f"device used by rand_tensor:\t{rand_tensor.device}")
rand_tensor = rand_tensor.to(device=torch_device)
print(f"device used by rand_tensor:\t{rand_tensor.device}")

device used by rand_tensor:	cpu
device used by rand_tensor:	cuda:0


To create a tensor directly in the GPU

In [37]:
rand_tensor = torch.rand(1000000, device=torch_device)
print(f"device used by rand_tensor:\t{rand_tensor.device}")

device used by rand_tensor:	cuda:0


In [39]:
torch.cuda.memory_allocated(0)

4000256

To check the GPU usage

In [53]:
if torch_device.type == 'cuda':
    print(torch.cuda.get_device_name(torch.cuda.current_device()))
    print('Memory Usage:')
    print('Allocated (in GB):\t', round(torch.cuda.memory_allocated(torch.cuda.current_device())/1024**3,3))
    print('Cached (in GB):\t\t', round(torch.cuda.memory_reserved(torch.cuda.current_device())/1024**3,3))
    print('Allocated (in byte):\t', torch.cuda.memory_allocated(torch.cuda.current_device()))
    print('Cached (in byte):\t', torch.cuda.memory_reserved(torch.cuda.current_device()))
    print(f'Maximum GPU memory occupied by tensors in bytes:\t\t{torch.cuda.max_memory_allocated()}')
    print(f'Maximum GPU memory managed by the caching allocator in bytes:\t{torch.cuda.max_memory_reserved()}')

NVIDIA GeForce RTX 2070 with Max-Q Design
Memory Usage:
Allocated (in GB):	 0.004
Cached (in GB):		 0.021
Allocated (in byte):	 4000256
Cached (in byte):	 23068672
Maximum GPU memory occupied by tensors in bytes:		4040704
Maximum GPU memory managed by the caching allocator in bytes:	23068672


# Tensors

Creation

In [68]:
rand_tensor = torch.rand(2,3)
ones_tensor = torch.ones(2,3)
zeros_tensor = torch.zeros(2,3)
full_tensor = torch.full((2,3),2)
tensor_from_numpy_array = torch.from_numpy(np.random.rand(2,3))
tensor_from_list = torch.tensor([[1,2,3],[4,5,6]])


print(f"rand_tensor:\n{rand_tensor}\n")
print(f"ones_tensor:\n{ones_tensor}\n")
print(f"zeros_tensor:\n{zeros_tensor}\n")
print(f"full_tensor:\n{full_tensor}\n")
print(f"tensor_from_numpy_array:\n{tensor_from_numpy_array}\n")
print(f"tensor_from_list:\n{tensor_from_list}\n")

rand_tensor:
tensor([[0.8494, 0.2287, 0.3451],
        [0.7794, 0.1065, 0.6900]])

ones_tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

zeros_tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

full_tensor:
tensor([[2, 2, 2],
        [2, 2, 2]])

tensor_from_numpy_array:
tensor([[0.5753, 0.1425, 0.4476],
        [0.1436, 0.2854, 0.3762]], dtype=torch.float64)

tensor_from_list:
tensor([[1, 2, 3],
        [4, 5, 6]])



Attributes

In [66]:
print(f'rand_tensor shape:\t{rand_tensor.shape}')
print(f'rand_tensor size:\t{rand_tensor.size()}')
print(f'rand_tensor dtype:\t{rand_tensor.dtype}')
print(f'rand_tensor device:\t{rand_tensor.device}')

rand_tensor shape:	torch.Size([2, 3])
rand_tensor size:	torch.Size([2, 3])
rand_tensor dtype:	torch.float32
rand_tensor device:	cpu


## Operations

In [79]:
ones_tensor = torch.ones(2,3).to(torch_device)
twos_tensor = torch.full((2,3),2).to(torch_device)

concat_tensor = torch.cat([ones_tensor, twos_tensor])
concat_tensor_dim_1 = torch.cat([ones_tensor, twos_tensor], dim=1)
stack_tensor = torch.stack([ones_tensor, twos_tensor])
stack_tensor_dim_1 = torch.stack([ones_tensor, twos_tensor],dim=1)

print(f'concat_tensor:\n{concat_tensor}\n')
print(f'concat_tensor_dim_1:\n{concat_tensor_dim_1}\n')
print(f'stack_tensor:\n{stack_tensor}\n')
print(f'stack_tensor_dim_1:\n{stack_tensor_dim_1}')

concat_tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')

concat_tensor_dim_1:
tensor([[1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.]], device='cuda:0')

stack_tensor:
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[2., 2., 2.],
         [2., 2., 2.]]], device='cuda:0')

stack_tensor_dim_1:
tensor([[[1., 1., 1.],
         [2., 2., 2.]],

        [[1., 1., 1.],
         [2., 2., 2.]]], device='cuda:0')


Slicing and indexing

In [88]:
concat_tensor[0::2,[0,2]]

tensor([[1., 1.],
        [2., 2.]], device='cuda:0')

Multiplycation

In [103]:
fours_tensor = torch.full((2,3),4).to(torch_device)

print(f'twos_tensor * fours_tensor:\n{twos_tensor * fours_tensor}\n')
print(f'twos_tensor.mul(fours_tensor):\n{twos_tensor.mul(fours_tensor)}')

twos_tensor * fours_tensor:
tensor([[8, 8, 8],
        [8, 8, 8]], device='cuda:0')

twos_tensor.mul(fours_tensor):
tensor([[8, 8, 8],
        [8, 8, 8]], device='cuda:0')
